### ISSUE TITLE
 I am having trouble using the z module in PowerShell. Can you help me identify and fix the problems?

### ISSUE THREAD

**Issue by epenflow** [badmotorfinger/z#67]
![image](https://github.com/user-attachments/assets/0cf43d68-2200-4faa-9f00-883e009a0441)

**Comment by badmotorfinger** [comment]
Hi @epenflow - Thanks for your report.

I can see you've got a heavily customized shell which can potentially conflict with this module. Can you please try stock standard PowerShell session and then perform a `Import-Module z` to see if it works? We can go from there.

**Comment by epenflow** [comment]
Hi, thanks for the response. I'm already disable all my powershell configurations but still the issue persits 
![image](https://github.com/user-attachments/assets/09972ed7-9445-4d8a-bf02-330dc8668cfa)
![image](https://github.com/user-attachments/assets/d7cc2545-e6ad-4304-a50d-38def1607f49)

**Comment by badmotorfinger** [comment]
1, Was working previously up until your crash?
2. Instead of `z someFolder` like in your screenshot, are you able to `cd someOtherFolder`? If you can then check the .cdHistory file to see if the entry has been made.

Without being able to remote into your machine to debug, the only thing I can suggest is to:

1. Delete the .cdHistory file
2. Delete z.psm1 module and the module folder it is within and then re-install z using `Install-Module z -AllowClobber`'

Let me know how you get on.

**Comment by epenflow** [comment]
Actually the cd and z command work but whenever i'm using z command it always thrown that error. I'm already try to reinstall it but still this issue persists maybe i'll try to delete cd history as you said.

**Comment by epenflow** [comment]
Thanks @badmotorfinger. Deleting .cdHistory resolved the issue

**Comment by badmotorfinger** [comment]
I'm glad it worked in the end, I was starting to get worried :)
